layout: "main"
logger: "console"
charset: "utf8"
appname: "Broadway"
route_cache: 0
template: "template_toolkit"
engines:
  template_toolkit:
    COMPILE_EXT: ".ttc" 
    COMPILE_DIR: "/tmp/ttcompile"

# broadway
broadway:
  title: "Perl Dancer"
  date: "Oct. 9, 2010"
  event: "OSDCfr 2010"
  author: "Alexis Sukrieh"
  slides: 52
  refresh_rate: 1300
  remote: 1

