layout: "main"
logger: "console"
charset: "utf8"
appname: "Broadway"
route_cache: 0
template: "template_toolkit"
engines:
  template_toolkit:
    COMPILE_EXT: ".ttc" 
    COMPILE_DIR: "/tmp/ttcompile"

# broadway
broadway:
  title: "Perl Object"
  date: "November, 2011"
  event: "@cPanel"
  author: "Nicolas Rochelemagne"
  slides: 28
  refresh_rate: 600
  remote: 0

