layout: "main"
logger: "console"
charset: "utf8"
appname: "Broadway"

# broadway
broadway:
  title: "Perl Dancer"
  date: "Oct. 9, 2010"
  event: "OSDCfr 2010"
  author: "Alexis Sukrieh"
  slides: 50
  refresh_rate: 500

